/**
 * Every user-visible string lives here. The interface is Dutch; the code is English.
 */
export const nl = {
  app: {
    naam: 'DUCs Playbook',
    ondertitel: 'Spelvarianten en drills voor DUC Dendermonde',
  },
  login: {
    kop: 'Welkom terug',
    uitleg: 'Log in met je e-mailadres en wachtwoord. Heb je er nog geen, vraag dan een inloglink.',
    emailLabel: 'E-mailadres',
    wachtwoordLabel: 'Wachtwoord',
    inloggen: 'Inloggen',
    knop: 'Stuur me een link',
    linkUitleg: 'Nog geen wachtwoord, of vergeten?',
    bezig: 'Bezig…',
    verstuurd: 'Er is een link onderweg naar',
    verstuurdUitleg:
      'Open hem op het toestel waar je wil werken. De link is één keer bruikbaar en vervalt na een uur.',
    opnieuw: 'Toch met een wachtwoord',
    fout: 'Dat lukte niet:',
    verkeerd:
      'Dat e-mailadres en wachtwoord horen niet bij elkaar. Heb je nog geen wachtwoord ingesteld, vraag dan hieronder een inloglink.',
    linkVerlopen: 'Die link werkt niet meer. Vraag hieronder een nieuwe aan.',
    afmelden: 'Afmelden',
  },
  account: {
    titel: 'Je account',
    terug: 'Terug naar de diagrammen',
    wachtwoordTitel: 'Wachtwoord',
    wachtwoordUitleg:
      'Met een wachtwoord log je op een nieuw toestel meteen in, zonder te wachten op een mail.',
    nieuw: 'Nieuw wachtwoord',
    herhaal: 'Nog eens',
    minimum: 'Minstens acht tekens.',
    teKort: 'Een wachtwoord van minstens acht tekens, graag.',
    verschillend: 'De twee velden zijn niet hetzelfde.',
    bewaren: 'Wachtwoord bewaren',
    bezig: 'Bezig…',
    bewaard: 'Je wachtwoord staat klaar. Vanaf nu log je in met je e-mailadres en dit wachtwoord.',
    fout: 'Dat lukte niet:',
    nudgeTitel: 'Stel een wachtwoord in',
    nudgeUitleg:
      'Dan hoef je op een nieuw toestel niet meer op een mailtje te wachten.',
    nudgeKnop: 'Instellen',
    nudgeLater: 'Later',
  },
  rechten: {
    trainer: 'Trainer, mag bewerken',
    speler: 'Speler, alleen lezen',
    spelerUitleg:
      'Je account heeft nog geen bewerkrechten. Vraag Daan om je als trainer aan te zetten.',
  },
  veld: {
    volledig: 'Volledig veld',
    half: 'Half veld',
    vrij: 'Vrij vlak',
    volledigUitleg: 'Liggend, beide endzones. Voor volledige spelvarianten.',
    halfUitleg: 'Staand, één endzone plus 32 meter. Voor endzone-sets en drills.',
    vrijUitleg: 'Geen lijnen. Voor drills zonder veldreferentie.',
  },
  slot: {
    bezet: 'Iemand is hier al bezig',
    bezetUitleg: (naam: string) =>
      `${naam} heeft dit diagram open. Om te vermijden dat jullie elkaars werk overschrijven, kan er maar één tegelijk in.`,
    bezetOnbekend: 'Iemand anders heeft dit diagram open.',
    bezetTip: 'Zodra hij of zij weg is, komt het binnen twee minuten vrij.',
    opnieuw: 'Opnieuw proberen',
    verloren: 'Je was even weg',
    verlorenUitleg:
      'Dit diagram is intussen vrijgekomen en iemand anders werkt eraan. Wat je nog niet had opgeslagen is niet bewaard.',
    verlorenAlleen:
      'Dit diagram is intussen vrijgekomen. Om te vermijden dat je iets overschrijft, ga je terug naar het overzicht.',
    naarOverzicht: 'Naar de diagrammen',
    controle: 'Even kijken of je erin kan…',
    fout: 'Kon niet nagaan of dit diagram vrij is:',
  },
  editor: {
    titel: 'Editor',
    terug: 'Terug',
    laden: 'Diagram laden…',
    zoomUit: 'Terug naar het hele veld',
    nietGeladen: 'Dit diagram kon niet geladen worden',
    nietsBewaard: 'Nog niets wordt bewaard. Herlaad je de pagina, dan is je werk weg.',
    selecteren: 'Selecteren',
    speler: 'Speler',
    pion: 'Pion',
    aanval: 'Aanval',
    verdediging: 'Verdediging',
    raster: 'Raster',
    rasterUitleg: 'Raster van een halve meter',
    naamPlaceholder: 'Naam van het diagram',
    ongedaan: 'Ongedaan',
    opnieuw: 'Opnieuw',
    verwijderen: 'Verwijderen',
    bezettingUitleg: 'Aanval en verdediging op het veld. Kleurt zodra het er geen zeven zijn.',
    hulp:
      'Tik een speler aan voor zijn menu; daar teken je zijn cut of zijn worp. Slepen verplaatst meteen.',
  },
  menu: {
    schijf: 'Schijf',
    instellingen: 'Instellingen',
    verwijderen: 'Verwijderen',
    kant: 'Kant',
    kantWisselen: 'Kant wisselen',
    positie: 'Positie',
    eigenLabel: 'Eigen label',
    eigenLabelLeeg: 'Positie',
    kleur: 'Kleur',
    typeWisselen: 'Type wisselen',
    worptype: 'Worptype',
    worptypeUitleg:
      'Bepaalt hoe de curve standaard buigt. Heb je de bocht zelf al versleept, dan blijft die staan.',
  },
  instellingen: {
    type: 'Type',
    categorie: 'Categorie',
    tokenstijl: 'Tokenstijl',
    letters: 'Letters',
    xo: 'X en O',
    blanco: 'Blanco',
    kies: 'Kies…',
    speelvariant: 'Speelvariant',
    drill: 'Drill',
    concept: 'Concept',
    conceptUitleg: 'Concept, alleen voor mij zichtbaar',
    meer: 'Meer',
    minder: 'Minder',
    nieuweSpeler: 'Nieuwe speler',
  },
  frames: {
    frame: 'Frame',
    kort: 'Frame',
    vorige: 'Vorig frame',
    toevoegenKort: 'Frame toevoegen',
    volgende: 'Volgend frame',
    toevoegen:
      'Voegt het volgende frame toe: iedereen met een cut of juke staat daar al op zijn eindpunt, en een aangekomen worp is doorgegeven.',
    geenBeweging:
      'Zet eerst een cut, een juke of een worp naar een ontvanger in dit frame. Zonder beweging zou het volgende frame een identieke kopie zijn.',
    maximum: 'Tien frames is het maximum.',
    duur: 'Duur',
    dupliceren: 'Dupliceren',
    verwijderen: 'Verwijderen',
    werktDoor: (n: number) =>
      n === 1 ? 'werkt door naar 1 volgend frame' : `werkt door naar ${n} volgende frames`,
    werktDoorUitleg:
      'Wat je in dit frame wijzigt, schuift mee in de frames erna. Verplaatsingen die je daar zelf al deed blijven behouden.',
  },
  afspelen: {
    speel: 'Afspelen',
    pauze: 'Pauzeren',
    scrubber: 'Positie in de animatie',
    lussen: 'Lussen',
    beide: 'Beide',
  },
  opslaan: {
    schoon: 'Nog niets gewijzigd',
    wachtend: 'Wijzigingen',
    bezig: 'Opslaan…',
    bewaard: 'Opgeslagen',
    fout: 'Opslaan mislukt',
  },
  validatie: {
    knop: 'nog te doen',
    titel: 'Voor dit diagram compleet is:',
    losseWorp: (n: number) =>
      n === 1
        ? 'Eén worp komt bij niemand aan. Sleep de punt op een speler of op het eind van zijn cut.'
        : `${n} worpen komen bij niemand aan. Sleep de punt op een speler of op het eind van zijn cut.`,
  },
  bibliotheek: {
    titel: 'Diagrammen',
    leegTitel: 'Nog geen diagrammen',
    leeg: 'Maak je eerste diagram. Je kiest een veld en een startopstelling, en de rest teken je erin.',
    leegSpeler: 'Zodra je trainer diagrammen aanmaakt, verschijnen ze hier.',
    geenVoorbeeld: 'Geen voorbeeld',
    nieuw: 'Nieuw diagram',
    concept: 'Concept',
    geenNaam: 'Naamloos diagram',
    openen: 'Openen',
    zoeken: 'Zoeken op naam of tag',
    zoekenPlaceholder: 'Zoek een diagram…',
    alles: 'Alles',
    speelvarianten: 'Speelvarianten',
    drills: 'Drills',
    favorieten: 'Favorieten',
    alleCategorieen: 'Alle categorieën',
    favorietAan: 'Bij favorieten zetten',
    favorietUit: 'Uit favorieten halen',
    verwijderen: 'Verwijderen',
    verwijderenVraag: 'Dit diagram en al zijn frames verdwijnen. Zeker?',
    verwijderenJa: 'Ja, verwijder',
    annuleren: 'Annuleren',
    verwijderenBezig: 'Bezig…',
    verwijderenFout: 'Verwijderen mislukt:',
    geenTreffers: 'Geen diagram komt hierop uit.',
    geenTreffersUitleg: 'Pas je zoekterm of je filters aan.',
    filtersWissen: 'Filters wissen',
    aantal: (n: number) => (n === 1 ? '1 diagram' : `${n} diagrammen`),
  },
  nieuw: {
    titel: 'Nieuw diagram',
    uitleg: 'Kies een veld en een startopstelling. De rest teken je in de editor.',
    veldtype: 'Welk veld?',
    opstelling: 'Waarmee begin je?',
    doorgaan: 'Doorgaan',
    bezig: 'Aanmaken…',
    fout: 'Aanmaken mislukt:',
    geenRechten:
      'Je account heeft geen bewerkrechten, dus je kan geen diagram aanmaken. Vraag Daan om je als trainer aan te zetten.',
  },
  bulk: {
    titel: 'Selectie bewerken',
    alles: 'Alles',
    spelers: 'Spelers',
    pionnen: 'Pionnen',
    arrows: 'Arrows',
    deselecteren: 'Deselecteren',
    dupliceren: 'Dupliceren',
    verwijderen: 'Verwijderen',
    gemengd: 'Gemengd',
    arrowtype: 'Arrowtype',
  },
  kleuren: {
    standaard: 'Standaard',
    geel: 'Geel',
    paars: 'Paars',
    wit: 'Wit',
    grijs: 'Grijs',
  },
  bouw: {
    stap: 'In aanbouw.',
    toelichting:
      'Het veld, het inloggen en het plaatsen van spelers en pionnen werken. Arrows, opslaan en de bibliotheek komen in de volgende stappen. Kies hieronder een startpunt om de editor te openen.',
  },
} as const
