/**
 * Every user-visible string lives here. The interface is Dutch; the code is English.
 */
export const nl = {
  app: {
    naam: 'DUCs Playbook',
    ondertitel: 'Spelvarianten en drills voor DUC Dendermonde',
  },
  login: {
    uitleg: 'Log in met je e-mailadres. Je krijgt een link, geen wachtwoord.',
    emailLabel: 'E-mailadres',
    knop: 'Stuur me een link',
    bezig: 'Bezig…',
    verstuurd: 'Er is een link onderweg naar',
    verstuurdUitleg:
      'Open hem op het toestel waar je wil werken. De link is één keer bruikbaar en vervalt na een uur.',
    fout: 'Dat lukte niet:',
    linkVerlopen: 'Die link werkt niet meer. Vraag hieronder een nieuwe aan.',
    afmelden: 'Afmelden',
  },
  rechten: {
    trainer: 'Trainer, mag bewerken',
    speler: 'Speler, alleen lezen',
    spelerUitleg:
      'Je account heeft nog geen bewerkrechten. Vraag Daan om je als trainer aan te zetten.',
  },
  veld: {
    volledig: 'Volledig veld',
    half: 'Half veld',
    vrij: 'Vrij vlak',
    volledigUitleg: 'Liggend, beide endzones. Voor volledige spelvarianten.',
    halfUitleg: 'Staand, één endzone plus 32 meter. Voor endzone-sets en drills.',
    vrijUitleg: 'Geen lijnen. Voor drills zonder veldreferentie.',
  },
  editor: {
    titel: 'Editor',
    terug: 'Terug',
    laden: 'Diagram laden…',
    zoomUit: 'Terug naar het hele veld',
    nietGeladen: 'Dit diagram kon niet geladen worden',
    nietsBewaard: 'Nog niets wordt bewaard. Herlaad je de pagina, dan is je werk weg.',
    selecteren: 'Selecteren',
    speler: 'Speler',
    pion: 'Pion',
    aanval: 'Aanval',
    verdediging: 'Verdediging',
    raster: 'Raster',
    rasterUitleg: 'Raster van een halve meter',
    naamPlaceholder: 'Naam van het diagram',
    ongedaan: 'Ongedaan',
    opnieuw: 'Opnieuw',
    verwijderen: 'Verwijderen',
    bezettingUitleg: 'Aanval en verdediging op het veld. Kleurt zodra het er geen zeven zijn.',
    hulp:
      'Kies een gereedschap en tik op het veld om te plaatsen. Slepen verplaatst meteen. Tik een speler aan voor het menu; daar teken je ook een cut, juke of worp. Van een arrow open je met de punt het menu en met het lijfje de handvatten. Twee vingers of ctrl met scrollen zoomt in.',
  },
  menu: {
    schijf: 'Schijf',
    instellingen: 'Instellingen',
    verwijderen: 'Verwijderen',
    kant: 'Kant',
    kantWisselen: 'Kant wisselen',
    positie: 'Positie',
    eigenLabel: 'Eigen label',
    eigenLabelLeeg: 'Positie',
    kleur: 'Kleur',
    typeWisselen: 'Type wisselen',
    worptype: 'Worptype',
    worptypeUitleg:
      'Bepaalt hoe de curve standaard buigt. Heb je de bocht zelf al versleept, dan blijft die staan.',
  },
  instellingen: {
    type: 'Type',
    categorie: 'Categorie',
    tokenstijl: 'Tokenstijl',
    letters: 'Letters',
    xo: 'X en O',
    blanco: 'Blanco',
    kies: 'Kies…',
    speelvariant: 'Speelvariant',
    drill: 'Drill',
    concept: 'Concept',
    conceptUitleg: 'Concept, alleen voor mij zichtbaar',
    meer: 'Meer',
    minder: 'Minder',
    nieuweSpeler: 'Nieuwe speler',
  },
  frames: {
    frame: 'Frame',
    kort: 'Frame',
    vorige: 'Vorig frame',
    volgende: 'Volgend frame',
    toevoegen: 'Voegt het volgende frame toe: iedereen met een cut of juke staat daar al op zijn eindpunt.',
    geenBeweging:
      'Zet eerst een cut of een juke in dit frame. Zonder beweging zou het volgende frame een identieke kopie zijn.',
    maximum: 'Tien frames is het maximum.',
    duur: 'Duur',
    dupliceren: 'Dupliceren',
    verwijderen: 'Verwijderen',
    werktDoor: (n: number) =>
      n === 1 ? 'werkt door naar 1 volgend frame' : `werkt door naar ${n} volgende frames`,
    werktDoorUitleg:
      'Wat je in dit frame wijzigt, schuift mee in de frames erna. Verplaatsingen die je daar zelf al deed blijven behouden.',
  },
  afspelen: {
    speel: 'Afspelen',
    pauze: 'Pauzeren',
    scrubber: 'Positie in de animatie',
    lussen: 'Lussen',
    beide: 'Beide',
  },
  opslaan: {
    schoon: 'Nog niets gewijzigd',
    wachtend: 'Wijzigingen',
    bezig: 'Opslaan…',
    bewaard: 'Opgeslagen',
    fout: 'Opslaan mislukt',
  },
  validatie: {
    knop: 'nog te doen',
    titel: 'Voor dit diagram compleet is:',
  },
  bibliotheek: {
    titel: 'Diagrammen',
    leegTitel: 'Nog geen diagrammen',
    leeg: 'Maak je eerste diagram. Je kiest een veld en een startopstelling, en de rest teken je erin.',
    leegSpeler: 'Zodra je trainer diagrammen aanmaakt, verschijnen ze hier.',
    geenVoorbeeld: 'Geen voorbeeld',
    nieuw: 'Nieuw diagram',
    concept: 'Concept',
    geenNaam: 'Naamloos diagram',
    openen: 'Openen',
    zoeken: 'Zoeken op naam of tag',
    zoekenPlaceholder: 'Zoek een diagram…',
    alles: 'Alles',
    speelvarianten: 'Speelvarianten',
    drills: 'Drills',
    favorieten: 'Favorieten',
    alleCategorieen: 'Alle categorieën',
    favorietAan: 'Bij favorieten zetten',
    favorietUit: 'Uit favorieten halen',
    verwijderen: 'Verwijderen',
    verwijderenVraag: 'Dit diagram en al zijn frames verdwijnen. Zeker?',
    verwijderenJa: 'Ja, verwijder',
    annuleren: 'Annuleren',
    verwijderenBezig: 'Bezig…',
    verwijderenFout: 'Verwijderen mislukt:',
    geenTreffers: 'Geen diagram komt hierop uit.',
    geenTreffersUitleg: 'Pas je zoekterm of je filters aan.',
    filtersWissen: 'Filters wissen',
    aantal: (n: number) => (n === 1 ? '1 diagram' : `${n} diagrammen`),
  },
  nieuw: {
    titel: 'Nieuw diagram',
    veldtype: 'Welk veld?',
    opstelling: 'Waarmee begin je?',
    doorgaan: 'Doorgaan',
    bezig: 'Aanmaken…',
    fout: 'Aanmaken mislukt:',
    geenRechten:
      'Je account heeft geen bewerkrechten, dus je kan geen diagram aanmaken. Vraag Daan om je als trainer aan te zetten.',
  },
  bulk: {
    titel: 'Selectie bewerken',
    alles: 'Alles',
    spelers: 'Spelers',
    pionnen: 'Pionnen',
    arrows: 'Arrows',
    deselecteren: 'Deselecteren',
    dupliceren: 'Dupliceren',
    verwijderen: 'Verwijderen',
    gemengd: 'Gemengd',
    arrowtype: 'Arrowtype',
  },
  kleuren: {
    standaard: 'Standaard',
    geel: 'Geel',
    paars: 'Paars',
    wit: 'Wit',
    grijs: 'Grijs',
  },
  bouw: {
    stap: 'In aanbouw.',
    toelichting:
      'Het veld, het inloggen en het plaatsen van spelers en pionnen werken. Arrows, opslaan en de bibliotheek komen in de volgende stappen. Kies hieronder een startpunt om de editor te openen.',
  },
} as const
